# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/cilium/cilium"
  # This revision is post-1.1 which improves the k8s consts dependency so we
  # don't have to pull in a dependency on kubernetes. Should be updated to use
  # v1.2 on release.
  revision = "0a57282b9a59eabb4a553d1ebc0a18b89f4dab1e"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  revision = "v1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "92ea23a837e66f46ac9e7d04fa826602b7b0a42d"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "7538d73b4eb9511d85a9f1dfef202eeb8ac260f4"

# The below are transitive dependencies inherited from the Cilium deps.
[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision = "63ca7e48f59f463578ae6b6e839bef6906f048e2"

[[override]]
  name = "github.com/evalphobia/logrus_fluent"
  revision = "v0.4.0"

[[override]]
  name = "github.com/fatih/color"
  revision = "533cd7fd8a85905f67a1753afb4deddc85ea174f"

[[override]]
  name = "github.com/go-openapi/errors"
  revision = "fc3f73a224499b047eda7191e5d22e1e9631e86f"

[[override]]
  name = "github.com/go-openapi/loads"
  revision = "bf98340e04734f11563fd3008e87be4c1d4ffc08"

[[override]]
  name = "github.com/go-openapi/runtime"
  revision = "bf2ff8f7150788b1c7256abb0805ba0410cbbabb"

# Once we update "github.com/go-openapi/runtime" we can remove this override
[[override]]
  name = "github.com/go-openapi/analysis"
  revision = "d5a75b7d751ca3f11ad5d93cfe97405f2c3f6a47"

[[override]]
  name = "github.com/go-openapi/spec"
  revision = "3a0434164aa36744c7ba29b822d36894a1e5ec96"

[[override]]
  name = "github.com/go-openapi/strfmt"
  revision = "0cb3db44c13bad3b3f567b762a66751972a310cc"

[[override]]
  name = "github.com/go-openapi/swag"
  revision = "96d7b9ebd181a1735a1c9ac87914f2b32fbf56c9"

[[override]]
  name = "github.com/go-openapi/validate"
  revision = "b11dbf889b64cf815a7e2667412df313f4a3f17b"

[[override]]
  name = "github.com/sasha-s/go-deadlock"
  revision = "master"

[[override]]
  name = "golang.org/x/crypto"
  revision = "847319b7fc94cab682988f93da778204da164588"

[[override]]
  name = "golang.org/x/net"
  revision = "0744d001aa8470aaa53df28d32e5ceeb8af9bd70"

[[override]]
  name = "golang.org/x/sys"
  revision = "d8f5ea21b9295e315e612b4bcf4bedea93454d4d"
